### ISSUE TITLE
Access to OpenPCDet version from docker

### ISSUE THREAD

**Issue by deeptibhegde** [PRBonn/TARL#10]
Hello,
Would it be possible to have access to the OpenPCDet code (model files + config files) with the MinkUNet-PartA2 implementation ? I am unable to run the docker, I wish to run it in an anaconda env, which I have working already.

**Comment by nuneslu** [comment]
Unfortunately we don't have a forked version of the OpenPCDet with our changes, all our changes are in the provided docker image. You can use docker cp command to copy the files from the container to the host machine and then set it up with conda to run it in the host instead of the container.
