### ISSUE TITLE
The version of torch and MinkowskiEngine

### ISSUE THREAD

**Issue by dachengxiaocheng** [PRBonn/TARL#4]
Hey, 

Many thanks for releasing the code. Amazing work! 

May I ask what is the exact torch version and MinkowskiEngine? I followed the install command "pip3 install -r requirements.txt" and then "pip3 install -U -e .",  "python3 tarl_train.py"

But it shows "ModuleNotFoundError: No module named 'torch.ao.quantization'"

It seems that there is some error with torch====1.9.0

Thank you.

**Comment by nuneslu** [comment]
Could you tell me the version of CUDA you have in your machine? I would refer to this issue in our previous work: https://github.com/PRBonn/segcontrast/issues/11

Besides that, could you share the full error?

**Comment by dachengxiaocheng** [comment]
Hello, thanks for the quick replying!

My CUDA version is 11.7. 

I following your solution in your previous work by:
1.  pip3 install torch==1.9.0+cu111 torchvision==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html
2.  pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine 
("pip3 install -U git+https://github.com/NVIDIA/MinkowskiEngine --install-option="--blas=openblas" -v --no-deps" will show "no such option: --install-option") 

It gives a new error as below:

File "/home/henry/miniconda3/envs/test_env/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'MinkowskiConvolutionFunction' object

Thank you so much

**Comment by nuneslu** [comment]
In my setup I have used CUDA 11.1 and python3.8
Since it seems you are using conda, could you try to use those versions of CUDA and python and try installing again pytorch 1.9.0 and MinkowskiEngine?

**Comment by nuneslu** [comment]
I will close this issue now due to inactivity but feel free to reopen it if you are still face problems with the installation.
