### ISSUE TITLE
Reproducing Object Detection results

### ISSUE THREAD

**Issue by CSautier** [PRBonn/TARL#6]
Hi,
In your repo you provide a docker image for reproducing the object detection results with your modified version of OpenPCDet, and mention the KITTI launch command calling the config file "tarl_pretrained.yaml".
However I can't file this config file for kitti in the code, what I can find though are "tarl.yaml", "segcontrast.yaml" and "segcontrast_pretrained.yaml", and they differ by their batch size (2 for the two firsts, 8 for the last).

I assume the batch size should be of 8, but cannot be absolutely certain considering the absence of the mentioned config file.

Could you kindly confirm which batch size you used to produce Table 6 in your paper?

Best,

**Comment by nuneslu** [comment]
Hi, indeed the correct config file is not in the docker image, thanks for letting me know. The correct batch size for the object detection experiment was 4.

**Comment by nuneslu** [comment]
Hi again, sorry for the delay but I just added the missing config files in the docker image, so you should be able to train with the exact same parameters. :)
