### ISSUE TITLE
Which model do you load for downstream tasks? model_q or model_k?

### ISSUE THREAD

**Issue by codename1995** [PRBonn/TARL#8]
Hi,

when I finetune your TARL pre-trained model on downsteam tasks, I notice that there are two models saved, model_q (online updated model) and model_k (momentum updated model). Which one do you load for down-stream tasks?

**Comment by nuneslu** [comment]
Hi! We load model_q you can check how we save it in this function: https://github.com/PRBonn/TARL/blob/7f883d658d52bfbedf531727bebcd78bdbdfb3a1/tarl/models/models.py#L52

**Comment by codename1995** [comment]
Thank you for your reply.

The code you quote is only used once at the begining of training. After that, the ckpts are saved by
https://github.com/PRBonn/TARL/blob/7f883d658d52bfbedf531727bebcd78bdbdfb3a1/tarl/tarl_train.py#L47
I think that is the reason why there are both model_q and model_k in the ckpts.
